version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Testing things"
      - run: npm install
      - run: npm test
    hithere:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "helloooooo"
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
